name: turbo_firestore_api
description: A clean and efficient approach to dealing with data from Firestore.
version: 0.8.1
homepage: https://github.com/its-brianwithai/turbo_firestore_api
repository: https://github.com/its-brianwithai/turbo_firestore_api
issue_tracker: https://github.com/its-brianwithai/turbo_firestore_api/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

  loglytics: ^0.16.1
  turbo_response: ^0.2.6
  informers: ^0.0.3+2

dev_dependencies:
  fake_cloud_firestore: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
