name: turbo_firestore_api
description: A clean and efficient approach to dealing with data from Firestore.
version: 0.6.1
homepage: https://github.com/ultrawideturbodev/turbo_firestore_api
repository: https://github.com/codaveto/turbo_firestore_api
issue_tracker: https://github.com/ultrawideturbodev/turbo_firestore_api/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

  loglytics:
    git:
      url: git@github.com:ultrawideturbodev/loglytics.git
      ref: dev
  turbo_response:
    git:
      url: git@github.com:ultrawideturbodev/turbo_response.git
      ref: dev
  informers:
    git:
      url: git@github.com:ultrawideturbodev/informers.git
      ref: dev


dev_dependencies:
  fake_cloud_firestore: ^3.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

# The following section is automatically managed by toggle_dependencies.dart
dependency_overrides:
  informers:
    path: ../informers
  loglytics:
    path: ../loglytics
  turbo_firestore_api:
    path: 
  turbo_response:
    path: ../turbo_response
  veto:
    path: ../veto
  shadcn_flutter:
    path: ../../forks/shadcn_flutter
