# 🤖 pewPewCLI Prompts Configuration
# This file defines the prompts used by pewPewCLI for AI interactions.
# The prompts use specific block characters and formatting for optimal AI responses.

# 📝 Prompt Configuration
# Structure Guide:
# 
# Simple String Format:
# prompt_name: "Content of the prompt"
#
# Value/Path Structure:
# prompt_name:
#   value: |
#     Content of the prompt
#     with multiple lines
#   act_paths:
#     - "/path/to/destination1.md"
#     - "/path/to/destination2.md"
#
# OR
#
# prompt_name:
#   path: ".pew/prompts/custom_prompt.md"
#   act_paths:
#     - "/path/to/destination1.md"
#     - "/path/to/destination2.md"
#
# The `act_paths` feature allows automatic copying of prompts to multiple destinations
# using the `pew act <prompt_name>` command. This is useful for:
#   * Setting up multiple AI contexts with the same prompt
#   * Deploying prompt templates to various systems
#   * Maintaining consistency across different AI interactions
#
# Usage Notes:
# - Using `value` provides the prompt content directly in the config file
# - Using `path` loads the prompt content from an external file
# - You must use either `value` OR `path`, not both
# - File paths in act_paths can be absolute or relative to the current directory

# Commit message prompt for generating git commit messages
commit_message:
  path: .pew/prompts/commit_message.md

# Example prompt with multiple destinations
# example_prompt:
#   value: |
#     This is an example prompt with multiple lines.
#     It will be copied to multiple destinations when using:
#     pew act example_prompt
#   act_paths:
#     - "./.ai/prompt1.md"
#     - "./.ai/prompt2.md"
#
# Example prompt loaded from a file
# file_example_prompt:
#   path: ".pew/prompts/example_prompt.md"
#   act_paths:
#     - "./.ai/prompt1.md"
#     - "./.ai/prompt2.md"

plan-act-dev:
  path: .pew/prompts/you_are_a_plan_act_developer.md
  act_paths:
    - ".cursorrules"
    - "CLAUDE.md"
    - ".windsurfrules"
    - ".junie/guidelines.md"

fast-dev:
  path: .pew/prompts/you_are_a_fast_developer.md
  act_paths:
    - ".cursorrules"
    - "CLAUDE.md"
    - ".windsurfrules"
    - ".junie/guidelines.md"

oop-dev:
  path: .pew/prompts/you_are_an_oop_developer.md
  act_paths:
    - ".cursorrules"
    - "CLAUDE.md"
    - ".windsurfrules"
    - ".junie/guidelines.md"

requirements-expert:
  path: .pew/prompts/you_are_a_requrements_expert.md
  act_paths:
    - ".cursorrules"
    - "CLAUDE.md"
    - ".windsurfrules"
    - ".junie/guidelines.md"