# Repository configurations for pew clone command
# Each entry defines a repository that can be cloned using 'pew clone <repo-key>'

# Auto-rules repository for applying coding standards
auto-rules:
  source: "https://github.com/bmadcode/cursor-auto-rules-agile-workflow.git"
  target: ".pew/auto-rules"
  pre-clone: "echo 'Starting auto-rules clone...'"
  post-clone: "echo 'Auto-rules clone completed!'"
  cleanup: false

# Example project repository
example-project:
  source: "https://github.com/example/project.git"
  target: "projects/example"
  pre-clone: "mkdir -p projects"
  post-clone: "cd projects/example && npm install"
  cleanup: false

# Temporary repository that will be removed after cloning
temp-repo:
  source: "https://github.com/example/temp-repo.git"
  target: ".pew/temp"
  pre-clone: "echo 'Cloning temporary repository...'"
  post-clone: "echo 'Temporary repository cloned!'"
  cleanup: true

# Minimal repository configuration (only source is required)
minimal-repo:
  source: "https://github.com/example/minimal.git"
